FROM htcondor/submit:9.0-el7

USER root

RUN mkdir -p /usr/local/share/ca-certificates /etc/condor /tmp/condor-cache && \
    chmod 700 /tmp/condor-cache

COPY htcondor_ca.crt /usr/local/share/ca-certificates/htcondor_ca.crt
COPY condor_config.local /etc/condor/condor_config.local

CMD ["/bin/bash"]
